trigger:
- none

name: Deploy App Registration Automation

variables:
  azureResourceManagerConnection: ICO-PROD-SERVICE-CONN
  subscription: IRRNDG-PROD-EM20-RGRP
  shouldUpdate: $false

pool:
  name: 'WIN-DEV-POOL'
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: powershell
    scriptLocation: inlineScript
    inlineScript: |
      az deployment group create --resource-group $(azureResourceGroup) -f $(templateFile) --parameters @parameters.json