trigger:
- none

name: Deploy App Registration Automation

variables:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN

pool:
  vmImage: 'windows-latest'
  
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: './AppRegistration.ps1'
    ScriptArguments: '-displayName IndigoMonitorApp-Automation -refObjectId 50a092f7-3eb3-4d89-b431-ebf8d1dbb447'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true