trigger:
- none

name: Deploy App Registration Automation

variables:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN
  subscription: WTW-IRRNDG-DEV
  shouldUpdate: $false
  duration: 10

pool:
  vmImage: 'windows-latest'
  
steps:
- task: AzureCLI@2
  displayName: 'Deploy App Registration Automation'
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: ps
    scriptPath: 'RenewAppRegistrationClientSecret.ps1'
    arguments: '-subscription $(subscription) -shouldUpdate $(shouldUpdate) -duration $(duration)'