trigger:
- none

name: Deploy App Registration Client Secret Renewal

variables:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN

parameters:
  - name: subscription
    displayName: 'Subscription'
    type: string
    default: WTW-IRRNDG-DEV
    values:
      - WTW-IRRNDG-DEV
      - WTW-IRRNDG-PROD

  - name: shouldUpdate
    displayName: 'Action Needed'
    type: string
    default: Display Expiring Client Secrets
    values:
      - Display Expiring Client Secrets
      - Display and Renew Expiring Client Secrets

  - name: duration
    displayName: 'Client Secrets new validity (in years), if client secrets should be renewed'
    type: number
    default: 1
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

pool:
  vmImage: 'windows-latest'

steps:
- ${{ if contains(parameters.shouldUpdate, 'Display Expiring Client Secrets') }}:
  - task: AzureCLI@2
    displayName: 'List App Registrations with less than 30 days of Client Secret validity'
    inputs:
      azureSubscription: $(azureResourceManagerConnection)
      scriptType: ps
      scriptPath: 'RenewAppRegistrationClientSecret.ps1'
      arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate $false -duration ${{ parameters.duration }}'

- ${{ if contains(parameters.shouldUpdate, 'Display and Renew Expiring Client Secrets') }}:
  - task: AzureCLI@2
    displayName: 'List App Registrations with less than 30 days of Client Secret validity'
    inputs:
      azureSubscription: $(azureResourceManagerConnection)
      scriptType: ps
      scriptPath: 'RenewAppRegistrationClientSecret.ps1'
      arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate $true -duration ${{ parameters.duration }}'
