trigger:
- none

name: Deploy App Registration Client Secret Renewal

pool:
  vmImage: 'windows-latest'

parameters:
  - name: subscription
    displayName: 'Subscription'
    type: string
    default: WTW-IRRNDG-DEV
    values:
      - WTW-IRRNDG-DEV
      - WTW-IRRNDG-PROD

  - name: shouldUpdate
    displayName: 'Action Needed'
    type: string
    default: Display Expiring Client Secrets
    values:
      - Display Expiring Client Secrets
      - Display and Renew Expiring Client Secrets

  - name: duration
    displayName: 'Client Secrets new validity (in years), if client secrets should be renewed'
    type: number
    default: 1
    values:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

variables:
  - name: azureResourceManagerConnection
    value: ICO-DEV-SERVICE-CONN
  - ${{ if contains(parameters.shouldUpdate, 'Display Expiring Client Secrets') }}:
    - name: shouldUpdate
      value: $false
  - ${{ if contains(parameters.shouldUpdate, 'Display and Renew Expiring Client Secrets') }}:
    - name: shouldUpdate
      value: $true

steps:
  - task: AzureCLI@2
    displayName: 'Display expiring client secrets with less than 30 days of validity'
    inputs:
      azureSubscription: $(azureResourceManagerConnection)
      scriptType: ps
      scriptPath: 'RenewAppRegistrationClientSecret.ps1'
      arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate $(shouldUpdate) -duration ${{ parameters.duration }}'
