trigger:
- none

name: Deploy App Registration Automation

variables:
  azureResourceManagerConnection: ICO-PROD-SERVICE-CONN
  subscription: WTW-IRRNDG-DEV
  shouldUpdate: $false
  duration: 10

pool:
  name: 'WIN-DEV-POOL'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '.\RenewAppRegistrationClientSecret.ps1'
    arguments: -subscription $(subscription) -shouldUpdate $(shouldUpdate) -duration $(duration)