trigger:
- none

name: Deploy App Registration Automation

variables:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN
  displayName: "IndigoMonitorApp-Automation"
  refObjectId: "50a092f7-3eb3-4d89-b431-ebf8d1dbb447"

pool:
  vmImage: 'windows-latest'
  
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    inline: |
      Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force
      Install-Module -Name AzureAD -AllowClobber -Scope CurrentUser -Force
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: './AppRegistration.ps1'
    ScriptArguments: 
      -displayName $(displayName)`
      -refOjbectId $(refObjectId)
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true