parameters:
  - name: appRegistrationAutomation
    displayName: 'Choose App Registration Automation'
    type: string
    default: Create App Registration
    values:
      - Create App Registration
      - Update App Registration
      - Renew App Registration Client Secret

stages:
  - ${{ if eq(parameters.appRegistrationAutomation, 'Create App Registration' ) }}:
    - template: template.yml
      parameters:
        stages:
          - "Stg A"
          - "Stg B"
  - ${{ if eq(parameters.appRegistrationAutomation, 'Update App Registration' ) }}:
    - template: template.yml 
      parameters:
        stages:
          - "Stg C"
          - "Stg D"
          - "Stg E"
  - ${{ if eq(parameters.appRegistrationAutomation, 'Renew App Registration Client Secret' ) }}:
    - template: renew-app-registration-client-secret.yml 
      parameters:
        - name: subscription
          displayName: 'Subscription'
          type: string
          default: WTW-IRRNDG-DEV
          values:
            - WTW-IRRNDG-DEV
            - WTW-IRRNDG-PROD

        - name: shouldUpdate
          displayName: 'Action Needed'
          type: string
          default: Display Expiring Client Secrets
          values:
            - Display Expiring Client Secrets
            - Display and Renew Expiring Client Secrets

        - name: duration
          displayName: 'Client Secrets new validity (in years), if client secrets should be renewed'
          type: number
          default: 1
          values:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10