trigger:
- none

name: Deploy App Registration Client Secret Renewal

variables:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN

parameters:
  - name: subscription
    displayName: 'Subscription'
    type: string
    default: WTW-IRRNDG-DEV
    values:
      - WTW-IRRNDG-DEV
      - WTW-IRRNDG-PROD
  - name: shouldUpdate
    displayName: 'Should App Registration Client Secrets renew?'
    type: boolean
    default: false
  - name: duration
    displayName: 'Client Secrets new expiration (in years) if App Registration Client Secrets should renew'
    type: number
    default: 1
    values:
    - 1
    - 2
    - 5
    - 10

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: 'List App Registrations with less than 30 days of Client Secret validity'
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    scriptType: ps
    scriptPath: 'RenewAppRegistrationClientSecret.ps1'
    arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate ${{ parameters.shouldUpdate }} -duration ${{ parameters.duration }}'