trigger:
- none

name: Deploy App Registration Automation

variables:
  - name: azureResourceManagerConnection
    value: ICO-DEV-SERVICE-CONN
  - name: name
    value: IndigoMonitorApp-Automation
  - name: owners
    value: MICHA6273_adm@towerswatson.com, KEVIN3349_ADM@willistowerswatson.com

pool:
  vmImage: 'windows-latest'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name Az -Scope CurrentUser -AllowClobber -Force
      Install-Module -Name AzureRM -Scope CurrentUser -AllowClobber -Force
      Uninstall-AzureRm
      Install-Module -Name AzureAD -Scope CurrentUser -AllowClobber -Force

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    Inline: 
      $context = Get-AzContext
      $token = Get-AzAccessToken -ResourceTypeName AadGraph
      Connect-AzureAD -AadAccessToken $token.Token -AccountId $context.Account.Id -TenantId $context.Tenant.Id
    azurePowerShellVersion: 'LatestVersion'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: './AppRegistration.ps1'
    ScriptArguments: 
      -name $(name)`
      -owners $(owners)
    azurePowerShellVersion: 'LatestVersion'