trigger:
- none

name: Deploy App Registration Automation

variables:
  - name: azureResourceManagerConnection
    value: ICO-DEV-SERVICE-CONN
  - name: subscription
    value: WTW-IRRNDG-DEV
  - name: shouldUpdate
    value: false
  - name: duration
    value: 100

pool:
  name: WIN-DEV-POOL
  
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: $(azureResourceManagerConnection)
    ScriptType: 'FilePath'
    ScriptPath: './AppRegistrationClientSecretRenewal.ps1'
    ScriptArguments: 
      -subscription $(subscription)`
      -shouldUpdate $(shouldUpdate)`
      -duration $(duration)
    azurePowerShellVersion: 'LatestVersion'