trigger:
- none

name: Deploy App Registration Automation

variables:
  - name: azureResourceManagerConnection
    value: ICO-DEV-SERVICE-CONN
  - name: subscription
    value: WTW-IRRNDG-DEV
  - name: shouldUpdate
    value: $false
  - name: duration
    value: 100

pool:
  name: WIN-DEV-POOL
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-Host | Select-Object Version