parameters:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN
  subscription: WTW-IRRNDG-DEV
  shouldUpdate: $false
  duration: 1

stages:
- stage: Renew App Registration Client Secret
  displayName: Renew App Registration Client Secret
  jobs:
  - job: Build
    pool:
      name: windows-latest
    steps:
      - task: AzureCLI@2
        displayName: 'Display expiring Client Secrets with less than 30 days of validity'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: 'RenewAppRegistrationClientSecret.ps1'
          arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate ${{ parameters.shouldUpdate }} -duration ${{ parameters.duration }}'