trigger:
- none

name: Deploy App Registration Client Secret Renewal

pool:
  vmImage: 'windows-latest'

variables:
  - name: azureResourceManagerConnection
    value: ICO-DEV-SERVICE-CONN
  - ${{ if contains(parameters.shouldUpdate, 'Display Expiring Client Secrets') }}:
    - name: shouldUpdate
      value: $false
  - ${{ if contains(parameters.shouldUpdate, 'Display and Renew Expiring Client Secrets') }}:
    - name: shouldUpdate
      value: $true

steps:
  - task: AzureCLI@2
    displayName: 'Display expiring Client Secrets with less than 30 days of validity'
    inputs:
      azureSubscription: $(azureResourceManagerConnection)
      scriptType: ps
      scriptPath: 'RenewAppRegistrationClientSecret.ps1'
      arguments: '-subscription ${{ parameters.subscription }} -shouldUpdate $(shouldUpdate) -duration ${{ parameters.duration }}'
