trigger:
- none

name: Deploy App Registration Automation

pool:
  vmImage: 'windows-latest'

parameters:
  - name: appRegistrationAutomation
    displayName: 'Choose App Registration Automation'
    type: string
    default: Create App Registration
    values:
      - Create App Registration
      - Update App Registration
      - Renew App Registration Client Secret

stages:
  - ${{ if eq(parameters.appRegistrationAutomation, 'Create App Registration' ) }}:
  - stage: Build
    jobs:
      - template: create-app-registration.yml
    
  - ${{ if eq(parameters.appRegistrationAutomation, 'Update App Registration' ) }}:
  - stage: Build
    jobs:
      - template: update-app-registration.yml
  
  - ${{ if eq(parameters.appRegistrationAutomation, 'Renew App Registration Client Secret' ) }}:
  - stage: Build
    jobs:
      - template: renew-app-registration-client-secret.yml