parameters:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN

stages:
- stage: Build
  displayName: Create App Registration
  jobs:
  - job: Build
    variables:
    - group: APP-REGISTRATION-CREATE-VARS
    pool:
       vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        displayName: 'Create App Registration'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/CreateAppRegistration.ps1'
          arguments: '-subscription $(subscription) -name $(name) -owners $(owners) -keyVault $(keyVault) -apiPermissions $(apiPermissions) -replyUrls $(replyUrls)'