parameters:
  azureResourceManagerConnection: ICO-DEV-SERVICE-CONN

variables:
- group: APP-REGISTRATION-CLIENT-SECRET-RENEWAL-VARS

stages:
- stage: Renew
  displayName: Renew App Registration Client Secret
  jobs:
  - job: Renew App Registration Client Secret
    pool:
       vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        displayName: 'Renew App Registration Client Secret'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: '../scripts/RenewAppRegistrationClientSecret.ps1'
          arguments: '-subscription $(subscription) -shouldUpdate $(shouldUpdate) -duration $(duration)'