parameters:
- name: azureResourceManagerConnection
  type: string
  default: ICO-DEV-SERVICE-CONN

stages:
- stage: Build
  displayName: Renew App Registration Client Secret
  jobs:
  - job: Build
    variables:
    - group: APP-REGISTRATION-CLIENT-SECRET-RENEWAL-VARS
    pool:
       vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        displayName: 'Renew App Registration Client Secret'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/RenewAppRegistrationClientSecret.ps1'
          arguments: '-subscription $(subscription) -shouldUpdate $(shouldUpdate) -duration $(duration)'