parameters:
- name: azureResourceManagerConnection
  type: string
  default: ICO-DEV-SERVICE-CONN

stages:
- stage: Build
  displayName: Update App Registration
  jobs:
  - job: Build
    variables:
    - group: APP-REGISTRATION-UPDATE-VARS
    pool:
       vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        displayName: 'Update App Registration'
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: ps
          scriptPath: '$(System.DefaultWorkingDirectory)/scripts/UpdateAppRegistration.ps1'
          arguments: '-subscription $(subscription) -appId $(appId) -resetProperties $(resetProperties) -owners $(owners) -apiPermissions $(apiPermissions) -replyUrls $(replyUrls)'